// Code generated by go generate; DO NOT EDIT.
'use strict';

const SQL_VERBS = new Set([
    "ALTER",
    "BACKUP",
    "CREATE",
    "COMMIT",
    "DELETE",
    "DROP",
    "EXEC",
    "GRANT",
    "INSERT",
    "MOUNT",
    "REVOKE",
    "ROLLBACK",
    "SAVEPOINT",
    "SELECT",
    "TRUNCATE",
    "UNMOUNT",
    "UPDATE",
]);

module.exports = {
    SQL_VERBS,
};
