root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = [
    "machsvr",
  ]
  bin = "./tmp/machsvr"
  cmd = "make -f Makefile machsvr"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata", "vender", "packages"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  include_ext = ["go", "tpl", "tmpl", "html", "hcl"]
  follow_symlink = false
  full_bin = ""
  include_dir = []
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
