package tailer

// Predefined terminal themes

// ThemeSolarizedDark provides the Solarized Dark color scheme
var ThemeSolarizedDark = TerminalTheme{
	Background:          "#002b36",
	Foreground:          "#839496",
	Cursor:              "#839496",
	CursorAccent:        "#002b36",
	SelectionBackground: "#073642",
	Black:               "#073642",
	Red:                 "#dc322f",
	Green:               "#859900",
	Yellow:              "#b58900",
	Blue:                "#268bd2",
	Magenta:             "#d33682",
	Cyan:                "#2aa198",
	White:               "#eee8d5",
	BrightBlack:         "#002b36",
	BrightRed:           "#cb4b16",
	BrightGreen:         "#586e75",
	BrightYellow:        "#657b83",
	BrightBlue:          "#839496",
	BrightMagenta:       "#6c71c4",
	BrightCyan:          "#93a1a1",
	BrightWhite:         "#fdf6e3",
}

// ThemeSolarizedLight provides the Solarized Light color scheme
var ThemeSolarizedLight = TerminalTheme{
	Background:          "#fdf6e3",
	Foreground:          "#657b83",
	Cursor:              "#657b83",
	CursorAccent:        "#fdf6e3",
	SelectionBackground: "#eee8d5",
	Black:               "#073642",
	Red:                 "#dc322f",
	Green:               "#859900",
	Yellow:              "#b58900",
	Blue:                "#268bd2",
	Magenta:             "#d33682",
	Cyan:                "#2aa198",
	White:               "#eee8d5",
	BrightBlack:         "#002b36",
	BrightRed:           "#cb4b16",
	BrightGreen:         "#586e75",
	BrightYellow:        "#657b83",
	BrightBlue:          "#839496",
	BrightMagenta:       "#6c71c4",
	BrightCyan:          "#93a1a1",
	BrightWhite:         "#fdf6e3",
}

// ThemeMolokai provides the Molokai color scheme
var ThemeMolokai = TerminalTheme{
	Background:          "#1b1d1e",
	Foreground:          "#f8f8f2",
	Cursor:              "#f8f8f0",
	CursorAccent:        "#1b1d1e",
	SelectionBackground: "#49483e",
	Black:               "#1b1d1e",
	Red:                 "#f92672",
	Green:               "#a6e22e",
	Yellow:              "#e6db74",
	Blue:                "#66d9ef",
	Magenta:             "#ae81ff",
	Cyan:                "#a1efe4",
	White:               "#f8f8f2",
	BrightBlack:         "#75715e",
	BrightRed:           "#f92672",
	BrightGreen:         "#a6e22e",
	BrightYellow:        "#e6db74",
	BrightBlue:          "#66d9ef",
	BrightMagenta:       "#ae81ff",
	BrightCyan:          "#a1efe4",
	BrightWhite:         "#f9f8f5",
}

// ThemeUbuntu provides the Ubuntu terminal color scheme
var ThemeUbuntu = TerminalTheme{
	Background:          "#300a24",
	Foreground:          "#ffffff",
	Cursor:              "#ffffff",
	CursorAccent:        "#300a24",
	SelectionBackground: "#b3d4fc",
	Black:               "#2e3436",
	Red:                 "#cc0000",
	Green:               "#4e9a06",
	Yellow:              "#c4a000",
	Blue:                "#3465a4",
	Magenta:             "#75507b",
	Cyan:                "#06989a",
	White:               "#d3d7cf",
	BrightBlack:         "#555753",
	BrightRed:           "#ef2929",
	BrightGreen:         "#8ae234",
	BrightYellow:        "#fce94f",
	BrightBlue:          "#729fcf",
	BrightMagenta:       "#ad7fa8",
	BrightCyan:          "#34e2e2",
	BrightWhite:         "#eeeeec",
}

// ThemeDefault provides a standard dark terminal color scheme
var ThemeDefault = TerminalTheme{
	Background:          "#1e1e1e",
	Foreground:          "#ffffff",
	Cursor:              "#ffffff",
	CursorAccent:        "#1e1e1e",
	SelectionBackground: "#264f78",
	Black:               "#000000",
	Red:                 "#cd3131",
	Green:               "#0dbc79",
	Yellow:              "#e5e510",
	Blue:                "#2472c8",
	Magenta:             "#bc3fbc",
	Cyan:                "#11a8cd",
	White:               "#e5e5e5",
	BrightBlack:         "#666666",
	BrightRed:           "#f14c4c",
	BrightGreen:         "#23d18b",
	BrightYellow:        "#f5f543",
	BrightBlue:          "#3b8eea",
	BrightMagenta:       "#d670d6",
	BrightCyan:          "#29b8db",
	BrightWhite:         "#ffffff",
}
