package tailer

// Predefined terminal themes

// ThemeSolarizedDark provides the Solarized Dark color scheme
var ThemeSolarizedDark = TerminalTheme{
	Background:          "#002b36",
	Foreground:          "#839496",
	Cursor:              "#839496",
	CursorAccent:        "#002b36",
	SelectionBackground: "#073642",
	Black:               "#073642",
	Red:                 "#dc322f",
	Green:               "#859900",
	Yellow:              "#b58900",
	Blue:                "#268bd2",
	Magenta:             "#d33682",
	Cyan:                "#2aa198",
	White:               "#eee8d5",
	BrightBlack:         "#002b36",
	BrightRed:           "#cb4b16",
	BrightGreen:         "#586e75",
	BrightYellow:        "#657b83",
	BrightBlue:          "#839496",
	BrightMagenta:       "#6c71c4",
	BrightCyan:          "#93a1a1",
	BrightWhite:         "#fdf6e3",
}

// ThemeSolarizedLight provides the Solarized Light color scheme
var ThemeSolarizedLight = TerminalTheme{
	Background:          "#fdf6e3",
	Foreground:          "#1f4755",
	Cursor:              "#657b83",
	CursorAccent:        "#fdf6e3",
	SelectionBackground: "#eee8d5",
	Black:               "#073642",
	Red:                 "#dc322f",
	Green:               "#859900",
	Yellow:              "#b58900",
	Blue:                "#268bd2",
	Magenta:             "#d33682",
	Cyan:                "#2aa198",
	White:               "#eee8d5",
	BrightBlack:         "#002b36",
	BrightRed:           "#cb4b16",
	BrightGreen:         "#586e75",
	BrightYellow:        "#657b83",
	BrightBlue:          "#839496",
	BrightMagenta:       "#6c71c4",
	BrightCyan:          "#93a1a1",
	BrightWhite:         "#fdf6e3",
}

// ThemeMolokai provides the Molokai color scheme
var ThemeMolokai = TerminalTheme{
	Background:          "#1b1d1e",
	Foreground:          "#f8f8f2",
	Cursor:              "#f8f8f0",
	CursorAccent:        "#1b1d1e",
	SelectionBackground: "#49483e",
	Black:               "#1b1d1e",
	Red:                 "#f92672",
	Green:               "#a6e22e",
	Yellow:              "#e6db74",
	Blue:                "#66d9ef",
	Magenta:             "#ae81ff",
	Cyan:                "#a1efe4",
	White:               "#f8f8f2",
	BrightBlack:         "#75715e",
	BrightRed:           "#f92672",
	BrightGreen:         "#a6e22e",
	BrightYellow:        "#e6db74",
	BrightBlue:          "#66d9ef",
	BrightMagenta:       "#ae81ff",
	BrightCyan:          "#a1efe4",
	BrightWhite:         "#f9f8f5",
}

// ThemeUbuntu provides the Ubuntu terminal color scheme
var ThemeUbuntu = TerminalTheme{
	Background:          "#300a24",
	Foreground:          "#ffffff",
	Cursor:              "#ffffff",
	CursorAccent:        "#300a24",
	SelectionBackground: "#b3d4fc",
	Black:               "#2e3436",
	Red:                 "#cc0000",
	Green:               "#4e9a06",
	Yellow:              "#c4a000",
	Blue:                "#3465a4",
	Magenta:             "#75507b",
	Cyan:                "#06989a",
	White:               "#d3d7cf",
	BrightBlack:         "#555753",
	BrightRed:           "#ef2929",
	BrightGreen:         "#8ae234",
	BrightYellow:        "#fce94f",
	BrightBlue:          "#729fcf",
	BrightMagenta:       "#ad7fa8",
	BrightCyan:          "#34e2e2",
	BrightWhite:         "#eeeeec",
}

// ThemeDefault provides a standard dark terminal color scheme
var ThemeDefault = TerminalTheme{
	Background:          "#1e1e1e",
	Foreground:          "#ffffff",
	Cursor:              "#ffffff",
	CursorAccent:        "#1e1e1e",
	SelectionBackground: "#264f78",
	Black:               "#000000",
	Red:                 "#cd3131",
	Green:               "#0dbc79",
	Yellow:              "#e5e510",
	Blue:                "#2472c8",
	Magenta:             "#bc3fbc",
	Cyan:                "#11a8cd",
	White:               "#e5e5e5",
	BrightBlack:         "#666666",
	BrightRed:           "#f14c4c",
	BrightGreen:         "#23d18b",
	BrightYellow:        "#f5f543",
	BrightBlue:          "#3b8eea",
	BrightMagenta:       "#d670d6",
	BrightCyan:          "#29b8db",
	BrightWhite:         "#ffffff",
}

// ThemeDracula provides the Dracula color scheme
var ThemeDracula = TerminalTheme{
	Background:          "#282a36",
	Foreground:          "#f8f8f2",
	Cursor:              "#f8f8f2",
	CursorAccent:        "#282a36",
	SelectionBackground: "#44475a",
	Black:               "#21222c",
	Red:                 "#ff5555",
	Green:               "#50fa7b",
	Yellow:              "#f1fa8c",
	Blue:                "#bd93f9",
	Magenta:             "#ff79c6",
	Cyan:                "#8be9fd",
	White:               "#f8f8f2",
	BrightBlack:         "#6272a4",
	BrightRed:           "#ff6e6e",
	BrightGreen:         "#69ff94",
	BrightYellow:        "#ffffa5",
	BrightBlue:          "#d6acff",
	BrightMagenta:       "#ff92df",
	BrightCyan:          "#a4ffff",
	BrightWhite:         "#ffffff",
}

// ThemeNordic provides the Nordic color scheme
var ThemeNordic = TerminalTheme{
	Background:          "#2e3440",
	Foreground:          "#d8dee9",
	Cursor:              "#d8dee9",
	CursorAccent:        "#2e3440",
	SelectionBackground: "#434c5e",
	Black:               "#3b4252",
	Red:                 "#bf616a",
	Green:               "#a3be8c",
	Yellow:              "#ebcb8b",
	Blue:                "#81a1c1",
	Magenta:             "#b48ead",
	Cyan:                "#88c0d0",
	White:               "#e5e9f0",
	BrightBlack:         "#4c566a",
	BrightRed:           "#bf616a",
	BrightGreen:         "#a3be8c",
	BrightYellow:        "#ebcb8b",
	BrightBlue:          "#81a1c1",
	BrightMagenta:       "#b48ead",
	BrightCyan:          "#8fbcbb",
	BrightWhite:         "#eceff4",
}
