//go:generate go run fx_generate.go

package tql

// Code generated by go generate; DO NOT EDIT.

import (
	"math"

	"github.com/machbase/neo-server/mods/codec/opts"
	"github.com/machbase/neo-server/mods/expression"
	"github.com/machbase/neo-server/mods/nums"
)

func NewNode(task *Task) *Node {
	x := &Node{task: task}
	x.functions = map[string]expression.Function{
		// context
		"context": x.gen_context,
		"key":     x.gen_key,
		"value":   x.gen_value,
		"values":  x.gen_values,
		"param":   x.gen_param,
		"payload": x.gen_payload,
		// math
		"abs":       x.gen_abs,
		"acos":      x.gen_acos,
		"acosh":     x.gen_acosh,
		"asin":      x.gen_asin,
		"asinh":     x.gen_asinh,
		"atan":      x.gen_atan,
		"atanh":     x.gen_atanh,
		"ceil":      x.gen_ceil,
		"cos":       x.gen_cos,
		"cosh":      x.gen_cosh,
		"exp":       x.gen_exp,
		"exp2":      x.gen_exp2,
		"floor":     x.gen_floor,
		"log":       x.gen_log,
		"log10":     x.gen_log10,
		"log2":      x.gen_log2,
		"max":       x.gen_max,
		"min":       x.gen_min,
		"mod":       x.gen_mod,
		"pow":       x.gen_pow,
		"pow10":     x.gen_pow10,
		"remainder": x.gen_remainder,
		"round":     x.gen_round,
		"sin":       x.gen_sin,
		"sinh":      x.gen_sinh,
		"sqrt":      x.gen_sqrt,
		"tan":       x.gen_tan,
		"tanh":      x.gen_tanh,
		"trunc":     x.gen_trunc,
		// nums
		"count":      nums.Count,
		"len":        nums.Len,
		"element":    nums.Element,
		"linspace":   x.gen_linspace,
		"linspace50": x.gen_linspace50,
		"meshgrid":   x.gen_meshgrid,
		// maps.time
		"period":         x.gen_period,
		"nullValue":      x.gen_nullValue,
		"time":           x.gen_time,
		"parseTime":      x.gen_parseTime,
		"timeAdd":        x.gen_timeAdd,
		"roundTime":      x.gen_roundTime,
		"range":          x.gen_range,
		"sqlTimeformat":  x.gen_sqlTimeformat,
		"ansiTimeformat": x.gen_ansiTimeformat,
		// maps.monad
		"TAKE":       x.gen_TAKE,
		"DROP":       x.gen_DROP,
		"FILTER":     x.gen_FILTER,
		"FLATTEN":    x.gen_FLATTEN,
		"GROUPBYKEY": x.gen_GROUPBYKEY,
		"POPKEY":     x.gen_POPKEY,
		"PUSHKEY":    x.gen_PUSHKEY,
		"MAPKEY":     x.gen_MAPKEY,
		"POPVALUE":   x.gen_POPVALUE,
		"PUSHVALUE":  x.gen_PUSHVALUE,
		"MAPVALUE":   x.gen_MAPVALUE,
		"TIMEWINDOW": x.gen_TIMEWINDOW,
		"SCRIPT":     x.gen_SCRIPT,
		"lazy":       x.gen_lazy,
		// maps.dbsrc
		"from":    x.gen_from,
		"limit":   x.gen_limit,
		"between": x.gen_between,
		"dump":    x.gen_dump,
		"QUERY":   x.gen_QUERY,
		"SQL":     x.gen_SQL,
		// maps.dbsink
		"table":  x.gen_table,
		"tag":    x.gen_tag,
		"INSERT": x.gen_INSERT,
		"APPEND": x.gen_APPEND,
		// maps.bridge
		"bridge":       x.gen_bridge,
		"BRIDGE_QUERY": x.gen_BRIDGE_QUERY,
		// maps.fourier
		"minHz": x.gen_minHz,
		"maxHz": x.gen_maxHz,
		"FFT":   x.gen_FFT,
		// maps.encoder
		"CSV":             x.gen_CSV,
		"JSON":            x.gen_JSON,
		"MARKDOWN":        x.gen_MARKDOWN,
		"HTML":            x.gen_HTML,
		"CHART":           x.gen_CHART,
		"CHART_LINE":      x.gen_CHART_LINE,
		"CHART_SCATTER":   x.gen_CHART_SCATTER,
		"CHART_BAR":       x.gen_CHART_BAR,
		"CHART_LINE3D":    x.gen_CHART_LINE3D,
		"CHART_BAR3D":     x.gen_CHART_BAR3D,
		"CHART_SURFACE3D": x.gen_CHART_SURFACE3D,
		"CHART_SCATTER3D": x.gen_CHART_SCATTER3D,
		// maps.bytes
		"separator": x.gen_separator,
		"trimspace": x.gen_trimspace,
		"file":      x.gen_file,
		"STRING":    x.gen_STRING,
		"BYTES":     x.gen_BYTES,
		// maps.csv
		"col":          x.gen_col,
		"field":        x.gen_field,
		"datetimeType": x.gen_datetimeType,
		"stringType":   x.gen_stringType,
		"doubleType":   x.gen_doubleType,
		"freq":         x.gen_freq,
		"oscillator":   x.gen_oscillator,
		"sphere":       x.gen_sphere,
		"FAKE":         x.gen_FAKE,
		// maps.input
		"INPUT": x.gen_INPUT,
		// maps.output
		"OUTPUT": x.gen_OUTPUT,
		// aliases
		"markArea":  x.fmMarkArea,
		"markXAxis": x.gen_markLineXAxisCoord,
		"markYAxis": x.gen_markLineYAxisCoord,
		"tz":        x.gen_tz,
		"sep":       x.gen_sep,
		// codec.opts
		"assetHost":          x.gen_assetHost,
		"autoRotate":         x.gen_autoRotate,
		"boxDrawBorder":      x.gen_boxDrawBorder,
		"boxSeparateColumns": x.gen_boxSeparateColumns,
		"boxStyle":           x.gen_boxStyle,
		"brief":              x.gen_brief,
		"briefCount":         x.gen_briefCount,
		"chartJson":          x.gen_chartJson,
		"columnTypes":        x.gen_columnTypes,
		"columns":            x.gen_columns,
		"dataZoom":           x.gen_dataZoom,
		"delimiter":          x.gen_delimiter,
		"global":             x.gen_global,
		"globalOptions":      x.gen_globalOptions,
		"gridSize":           x.gen_gridSize,
		"header":             x.gen_header,
		"heading":            x.gen_heading,
		"html":               x.gen_html,
		"inputStream":        x.gen_inputStream,
		"lineWidth":          x.gen_lineWidth,
		"logger":             x.gen_logger,
		"markAreaNameCoord":  x.gen_markAreaNameCoord,
		"markAreaXAxis":      x.gen_markAreaXAxis,
		"markAreaYAxis":      x.gen_markAreaYAxis,
		"markLineStyle":      x.gen_markLineStyle,
		"markLineXAxis":      x.gen_markLineXAxis,
		"markLineXAxisCoord": x.gen_markLineXAxisCoord,
		"markLineYAxis":      x.gen_markLineYAxis,
		"markLineYAxisCoord": x.gen_markLineYAxisCoord,
		"opacity":            x.gen_opacity,
		"outputStream":       x.gen_outputStream,
		"precision":          x.gen_precision,
		"rownum":             x.gen_rownum,
		"series":             x.gen_series,
		"seriesLabels":       x.gen_seriesLabels,
		"seriesOptions":      x.gen_seriesOptions,
		"showGrid":           x.gen_showGrid,
		"size":               x.gen_size,
		"substituteNull":     x.gen_substituteNull,
		"subtitle":           x.gen_subtitle,
		"tableName":          x.gen_tableName,
		"theme":              x.gen_theme,
		"timeLocation":       x.gen_timeLocation,
		"timeformat":         x.gen_timeformat,
		"title":              x.gen_title,
		"toolboxDataView":    x.gen_toolboxDataView,
		"toolboxDataZoom":    x.gen_toolboxDataZoom,
		"toolboxSaveAsImage": x.gen_toolboxSaveAsImage,
		"transcoder":         x.gen_transcoder,
		"transpose":          x.gen_transpose,
		"visualMap":          x.gen_visualMap,
		"visualMapColor":     x.gen_visualMapColor,
		"xAxis":              x.gen_xAxis,
		"yAxis":              x.gen_yAxis,
		"zAxis":              x.gen_zAxis,
	}
	return x
}

// gen_context
//
// syntax: context()
func (x *Node) gen_context(args ...any) (any, error) {
	if len(args) != 0 {
		return nil, ErrInvalidNumOfArgs("context", 0, len(args))
	}
	ret := x.GetContext()
	return ret, nil
}

// gen_key
//
// syntax: key()
func (x *Node) gen_key(args ...any) (any, error) {
	if len(args) != 0 {
		return nil, ErrInvalidNumOfArgs("key", 0, len(args))
	}
	ret := x.GetRecordKey()
	return ret, nil
}

// gen_value
//
// syntax: value(...interface {})
func (x *Node) gen_value(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "value", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.GetRecordValue(p0...)
}

// gen_values
//
// syntax: values()
func (x *Node) gen_values(args ...any) (any, error) {
	if len(args) != 0 {
		return nil, ErrInvalidNumOfArgs("values", 0, len(args))
	}
	return x.GetRecordValues()
}

// gen_param
//
// syntax: param(string)
func (x *Node) gen_param(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("param", 1, len(args))
	}
	p0, err := convString(args, 0, "param", "string")
	if err != nil {
		return nil, err
	}
	ret := x.GetRequestParam(p0)
	return ret, nil
}

// gen_payload
//
// syntax: payload()
func (x *Node) gen_payload(args ...any) (any, error) {
	if len(args) != 0 {
		return nil, ErrInvalidNumOfArgs("payload", 0, len(args))
	}
	ret := x.GetRequestPayload()
	return ret, nil
}

// gen_abs
//
// syntax: abs(float64)
func (x *Node) gen_abs(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("abs", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "abs", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Abs(p0)
	return ret, nil
}

// gen_acos
//
// syntax: acos(float64)
func (x *Node) gen_acos(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("acos", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "acos", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Acos(p0)
	return ret, nil
}

// gen_acosh
//
// syntax: acosh(float64)
func (x *Node) gen_acosh(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("acosh", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "acosh", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Acosh(p0)
	return ret, nil
}

// gen_asin
//
// syntax: asin(float64)
func (x *Node) gen_asin(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("asin", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "asin", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Asin(p0)
	return ret, nil
}

// gen_asinh
//
// syntax: asinh(float64)
func (x *Node) gen_asinh(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("asinh", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "asinh", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Asinh(p0)
	return ret, nil
}

// gen_atan
//
// syntax: atan(float64)
func (x *Node) gen_atan(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("atan", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "atan", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Atan(p0)
	return ret, nil
}

// gen_atanh
//
// syntax: atanh(float64)
func (x *Node) gen_atanh(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("atanh", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "atanh", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Atanh(p0)
	return ret, nil
}

// gen_ceil
//
// syntax: ceil(float64)
func (x *Node) gen_ceil(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("ceil", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "ceil", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Ceil(p0)
	return ret, nil
}

// gen_cos
//
// syntax: cos(float64)
func (x *Node) gen_cos(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("cos", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "cos", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Cos(p0)
	return ret, nil
}

// gen_cosh
//
// syntax: cosh(float64)
func (x *Node) gen_cosh(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("cosh", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "cosh", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Cosh(p0)
	return ret, nil
}

// gen_exp
//
// syntax: exp(float64)
func (x *Node) gen_exp(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("exp", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "exp", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Exp(p0)
	return ret, nil
}

// gen_exp2
//
// syntax: exp2(float64)
func (x *Node) gen_exp2(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("exp2", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "exp2", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Exp2(p0)
	return ret, nil
}

// gen_floor
//
// syntax: floor(float64)
func (x *Node) gen_floor(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("floor", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "floor", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Floor(p0)
	return ret, nil
}

// gen_log
//
// syntax: log(float64)
func (x *Node) gen_log(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("log", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "log", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Log(p0)
	return ret, nil
}

// gen_log10
//
// syntax: log10(float64)
func (x *Node) gen_log10(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("log10", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "log10", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Log10(p0)
	return ret, nil
}

// gen_log2
//
// syntax: log2(float64)
func (x *Node) gen_log2(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("log2", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "log2", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Log2(p0)
	return ret, nil
}

// gen_max
//
// syntax: max(float64, float64)
func (x *Node) gen_max(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("max", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "max", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "max", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Max(p0, p1)
	return ret, nil
}

// gen_min
//
// syntax: min(float64, float64)
func (x *Node) gen_min(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("min", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "min", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "min", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Min(p0, p1)
	return ret, nil
}

// gen_mod
//
// syntax: mod(float64, float64)
func (x *Node) gen_mod(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("mod", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "mod", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "mod", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Mod(p0, p1)
	return ret, nil
}

// gen_pow
//
// syntax: pow(float64, float64)
func (x *Node) gen_pow(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("pow", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "pow", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "pow", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Pow(p0, p1)
	return ret, nil
}

// gen_pow10
//
// syntax: pow10(int)
func (x *Node) gen_pow10(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("pow10", 1, len(args))
	}
	p0, err := convInt(args, 0, "pow10", "int")
	if err != nil {
		return nil, err
	}
	ret := math.Pow10(p0)
	return ret, nil
}

// gen_remainder
//
// syntax: remainder(float64, float64)
func (x *Node) gen_remainder(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("remainder", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "remainder", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "remainder", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Remainder(p0, p1)
	return ret, nil
}

// gen_round
//
// syntax: round(float64)
func (x *Node) gen_round(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("round", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "round", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Round(p0)
	return ret, nil
}

// gen_sin
//
// syntax: sin(float64)
func (x *Node) gen_sin(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("sin", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "sin", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Sin(p0)
	return ret, nil
}

// gen_sinh
//
// syntax: sinh(float64)
func (x *Node) gen_sinh(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("sinh", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "sinh", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Sinh(p0)
	return ret, nil
}

// gen_sqrt
//
// syntax: sqrt(float64)
func (x *Node) gen_sqrt(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("sqrt", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "sqrt", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Sqrt(p0)
	return ret, nil
}

// gen_tan
//
// syntax: tan(float64)
func (x *Node) gen_tan(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("tan", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "tan", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Tan(p0)
	return ret, nil
}

// gen_tanh
//
// syntax: tanh(float64)
func (x *Node) gen_tanh(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("tanh", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "tanh", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Tanh(p0)
	return ret, nil
}

// gen_trunc
//
// syntax: trunc(float64)
func (x *Node) gen_trunc(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("trunc", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "trunc", "float64")
	if err != nil {
		return nil, err
	}
	ret := math.Trunc(p0)
	return ret, nil
}

// gen_linspace
//
// syntax: linspace(float64, float64, int)
func (x *Node) gen_linspace(args ...any) (any, error) {
	if len(args) != 3 {
		return nil, ErrInvalidNumOfArgs("linspace", 3, len(args))
	}
	p0, err := convFloat64(args, 0, "linspace", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "linspace", "float64")
	if err != nil {
		return nil, err
	}
	p2, err := convInt(args, 2, "linspace", "int")
	if err != nil {
		return nil, err
	}
	ret := x.fmLinspace(p0, p1, p2)
	return ret, nil
}

// gen_linspace50
//
// syntax: linspace50(float64, float64)
func (x *Node) gen_linspace50(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("linspace50", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "linspace50", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "linspace50", "float64")
	if err != nil {
		return nil, err
	}
	ret := x.fmLinspace50(p0, p1)
	return ret, nil
}

// gen_meshgrid
//
// syntax: meshgrid(, )
func (x *Node) gen_meshgrid(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("meshgrid", 2, len(args))
	}
	p0, err := convAny(args, 0, "meshgrid", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "meshgrid", "interface {}")
	if err != nil {
		return nil, err
	}
	ret := x.fmMeshgrid(p0, p1)
	return ret, nil
}

// gen_period
//
// syntax: period()
func (x *Node) gen_period(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("period", 1, len(args))
	}
	p0, err := convAny(args, 0, "period", "interface {}")
	if err != nil {
		return nil, err
	}
	return x.fmPeriod(p0)
}

// gen_nullValue
//
// syntax: nullValue()
func (x *Node) gen_nullValue(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("nullValue", 1, len(args))
	}
	p0, err := convAny(args, 0, "nullValue", "interface {}")
	if err != nil {
		return nil, err
	}
	ret := x.fmNullValue(p0)
	return ret, nil
}

// gen_time
//
// syntax: time()
func (x *Node) gen_time(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("time", 1, len(args))
	}
	p0, err := convAny(args, 0, "time", "interface {}")
	if err != nil {
		return nil, err
	}
	return x.fmTime(p0)
}

// gen_parseTime
//
// syntax: parseTime(string, string, )
func (x *Node) gen_parseTime(args ...any) (any, error) {
	if len(args) != 3 {
		return nil, ErrInvalidNumOfArgs("parseTime", 3, len(args))
	}
	p0, err := convString(args, 0, "parseTime", "string")
	if err != nil {
		return nil, err
	}
	p1, err := convString(args, 1, "parseTime", "string")
	if err != nil {
		return nil, err
	}
	p2, err := convTimeLocation(args, 2, "parseTime", "*time.Location")
	if err != nil {
		return nil, err
	}
	return x.fmParseTime(p0, p1, p2)
}

// gen_timeAdd
//
// syntax: timeAdd(, )
func (x *Node) gen_timeAdd(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("timeAdd", 2, len(args))
	}
	p0, err := convAny(args, 0, "timeAdd", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "timeAdd", "interface {}")
	if err != nil {
		return nil, err
	}
	return x.fmTimeAdd(p0, p1)
}

// gen_roundTime
//
// syntax: roundTime(, )
func (x *Node) gen_roundTime(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("roundTime", 2, len(args))
	}
	p0, err := convAny(args, 0, "roundTime", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "roundTime", "interface {}")
	if err != nil {
		return nil, err
	}
	return x.fmRoundTime(p0, p1)
}

// gen_range
//
// syntax: range(, , ...interface {})
func (x *Node) gen_range(args ...any) (any, error) {
	if len(args) < 2 {
		return nil, ErrInvalidNumOfArgs("range", 2, len(args))
	}
	p0, err := convAny(args, 0, "range", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "range", "interface {}")
	if err != nil {
		return nil, err
	}
	p2 := []interface{}{}
	for n := 2; n < len(args); n++ {
		argv, err := convAny(args, n, "range", "...interface {}")
		if err != nil {
			return nil, err
		}
		p2 = append(p2, argv)
	}
	return x.fmTimeRange(p0, p1, p2...)
}

// gen_sqlTimeformat
//
// syntax: sqlTimeformat(string)
func (x *Node) gen_sqlTimeformat(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("sqlTimeformat", 1, len(args))
	}
	p0, err := convString(args, 0, "sqlTimeformat", "string")
	if err != nil {
		return nil, err
	}
	ret := x.fmSqlTimeformat(p0)
	return ret, nil
}

// gen_ansiTimeformat
//
// syntax: ansiTimeformat(string)
func (x *Node) gen_ansiTimeformat(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("ansiTimeformat", 1, len(args))
	}
	p0, err := convString(args, 0, "ansiTimeformat", "string")
	if err != nil {
		return nil, err
	}
	ret := x.fmAnsiTimeformat(p0)
	return ret, nil
}

// gen_TAKE
//
// syntax: TAKE(...int)
func (x *Node) gen_TAKE(args ...any) (any, error) {
	p0 := []int{}
	for n := 0; n < len(args); n++ {
		argv, err := convInt(args, n, "TAKE", "...int")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmTake(p0...)
}

// gen_DROP
//
// syntax: DROP(...int)
func (x *Node) gen_DROP(args ...any) (any, error) {
	p0 := []int{}
	for n := 0; n < len(args); n++ {
		argv, err := convInt(args, n, "DROP", "...int")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmDrop(p0...)
}

// gen_FILTER
//
// syntax: FILTER(bool)
func (x *Node) gen_FILTER(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("FILTER", 1, len(args))
	}
	p0, err := convBool(args, 0, "FILTER", "bool")
	if err != nil {
		return nil, err
	}
	ret := x.fmFilter(p0)
	return ret, nil
}

// gen_FLATTEN
//
// syntax: FLATTEN()
func (x *Node) gen_FLATTEN(args ...any) (any, error) {
	if len(args) != 0 {
		return nil, ErrInvalidNumOfArgs("FLATTEN", 0, len(args))
	}
	ret := x.fmFlatten()
	return ret, nil
}

// gen_GROUPBYKEY
//
// syntax: GROUPBYKEY(...interface {})
func (x *Node) gen_GROUPBYKEY(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "GROUPBYKEY", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := x.fmGroupByKey(p0...)
	return ret, nil
}

// gen_POPKEY
//
// syntax: POPKEY(...int)
func (x *Node) gen_POPKEY(args ...any) (any, error) {
	p0 := []int{}
	for n := 0; n < len(args); n++ {
		argv, err := convInt(args, n, "POPKEY", "...int")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmPopKey(p0...)
}

// gen_PUSHKEY
//
// syntax: PUSHKEY()
func (x *Node) gen_PUSHKEY(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("PUSHKEY", 1, len(args))
	}
	p0, err := convAny(args, 0, "PUSHKEY", "interface {}")
	if err != nil {
		return nil, err
	}
	return x.fmPushKey(p0)
}

// gen_MAPKEY
//
// syntax: MAPKEY()
func (x *Node) gen_MAPKEY(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("MAPKEY", 1, len(args))
	}
	p0, err := convAny(args, 0, "MAPKEY", "interface {}")
	if err != nil {
		return nil, err
	}
	return x.fmMapKey(p0)
}

// gen_POPVALUE
//
// syntax: POPVALUE(...int)
func (x *Node) gen_POPVALUE(args ...any) (any, error) {
	p0 := []int{}
	for n := 0; n < len(args); n++ {
		argv, err := convInt(args, n, "POPVALUE", "...int")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmPopValue(p0...)
}

// gen_PUSHVALUE
//
// syntax: PUSHVALUE(int, , ...interface {})
func (x *Node) gen_PUSHVALUE(args ...any) (any, error) {
	if len(args) < 2 {
		return nil, ErrInvalidNumOfArgs("PUSHVALUE", 2, len(args))
	}
	p0, err := convInt(args, 0, "PUSHVALUE", "int")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "PUSHVALUE", "interface {}")
	if err != nil {
		return nil, err
	}
	p2 := []interface{}{}
	for n := 2; n < len(args); n++ {
		argv, err := convAny(args, n, "PUSHVALUE", "...interface {}")
		if err != nil {
			return nil, err
		}
		p2 = append(p2, argv)
	}
	return x.fmPushValue(p0, p1, p2...)
}

// gen_MAPVALUE
//
// syntax: MAPVALUE(int, , ...interface {})
func (x *Node) gen_MAPVALUE(args ...any) (any, error) {
	if len(args) < 2 {
		return nil, ErrInvalidNumOfArgs("MAPVALUE", 2, len(args))
	}
	p0, err := convInt(args, 0, "MAPVALUE", "int")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "MAPVALUE", "interface {}")
	if err != nil {
		return nil, err
	}
	p2 := []interface{}{}
	for n := 2; n < len(args); n++ {
		argv, err := convAny(args, n, "MAPVALUE", "...interface {}")
		if err != nil {
			return nil, err
		}
		p2 = append(p2, argv)
	}
	return x.fmMapValue(p0, p1, p2...)
}

// gen_TIMEWINDOW
//
// syntax: TIMEWINDOW(, , , ...interface {})
func (x *Node) gen_TIMEWINDOW(args ...any) (any, error) {
	if len(args) < 3 {
		return nil, ErrInvalidNumOfArgs("TIMEWINDOW", 3, len(args))
	}
	p0, err := convAny(args, 0, "TIMEWINDOW", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "TIMEWINDOW", "interface {}")
	if err != nil {
		return nil, err
	}
	p2, err := convAny(args, 2, "TIMEWINDOW", "interface {}")
	if err != nil {
		return nil, err
	}
	p3 := []interface{}{}
	for n := 3; n < len(args); n++ {
		argv, err := convAny(args, n, "TIMEWINDOW", "...interface {}")
		if err != nil {
			return nil, err
		}
		p3 = append(p3, argv)
	}
	ret := x.fmTimeWindow(p0, p1, p2, p3...)
	return ret, nil
}

// gen_SCRIPT
//
// syntax: SCRIPT(...interface {})
func (x *Node) gen_SCRIPT(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "SCRIPT", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmScript(p0...)
}

// gen_lazy
//
// syntax: lazy(bool)
func (x *Node) gen_lazy(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("lazy", 1, len(args))
	}
	p0, err := convBool(args, 0, "lazy", "bool")
	if err != nil {
		return nil, err
	}
	ret := x.fmLazy(p0)
	return ret, nil
}

// gen_from
//
// syntax: from(string, string, ...string)
func (x *Node) gen_from(args ...any) (any, error) {
	if len(args) < 2 {
		return nil, ErrInvalidNumOfArgs("from", 2, len(args))
	}
	p0, err := convString(args, 0, "from", "string")
	if err != nil {
		return nil, err
	}
	p1, err := convString(args, 1, "from", "string")
	if err != nil {
		return nil, err
	}
	p2 := []string{}
	for n := 2; n < len(args); n++ {
		argv, err := convString(args, n, "from", "...string")
		if err != nil {
			return nil, err
		}
		p2 = append(p2, argv)
	}
	ret := x.fmFrom(p0, p1, p2...)
	return ret, nil
}

// gen_limit
//
// syntax: limit(...int)
func (x *Node) gen_limit(args ...any) (any, error) {
	p0 := []int{}
	for n := 0; n < len(args); n++ {
		argv, err := convInt(args, n, "limit", "...int")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := x.fmLimit(p0...)
	return ret, nil
}

// gen_between
//
// syntax: between(, , ...interface {})
func (x *Node) gen_between(args ...any) (any, error) {
	if len(args) < 2 {
		return nil, ErrInvalidNumOfArgs("between", 2, len(args))
	}
	p0, err := convAny(args, 0, "between", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "between", "interface {}")
	if err != nil {
		return nil, err
	}
	p2 := []interface{}{}
	for n := 2; n < len(args); n++ {
		argv, err := convAny(args, n, "between", "...interface {}")
		if err != nil {
			return nil, err
		}
		p2 = append(p2, argv)
	}
	return x.fmBetween(p0, p1, p2...)
}

// gen_dump
//
// syntax: dump(...bool)
func (x *Node) gen_dump(args ...any) (any, error) {
	p0 := []bool{}
	for n := 0; n < len(args); n++ {
		argv, err := convBool(args, n, "dump", "...bool")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := x.fmDump(p0...)
	return ret, nil
}

// gen_QUERY
//
// syntax: QUERY(...interface {})
func (x *Node) gen_QUERY(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "QUERY", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmQuery(p0...)
}

// gen_SQL
//
// syntax: SQL(...interface {})
func (x *Node) gen_SQL(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "SQL", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmSql(p0...)
}

// gen_table
//
// syntax: table(string)
func (x *Node) gen_table(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("table", 1, len(args))
	}
	p0, err := convString(args, 0, "table", "string")
	if err != nil {
		return nil, err
	}
	ret := x.fmTable(p0)
	return ret, nil
}

// gen_tag
//
// syntax: tag(string, ...string)
func (x *Node) gen_tag(args ...any) (any, error) {
	if len(args) < 1 {
		return nil, ErrInvalidNumOfArgs("tag", 1, len(args))
	}
	p0, err := convString(args, 0, "tag", "string")
	if err != nil {
		return nil, err
	}
	p1 := []string{}
	for n := 1; n < len(args); n++ {
		argv, err := convString(args, n, "tag", "...string")
		if err != nil {
			return nil, err
		}
		p1 = append(p1, argv)
	}
	ret := x.fmTag(p0, p1...)
	return ret, nil
}

// gen_INSERT
//
// syntax: INSERT(...interface {})
func (x *Node) gen_INSERT(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "INSERT", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmInsert(p0...)
}

// gen_APPEND
//
// syntax: APPEND(...interface {})
func (x *Node) gen_APPEND(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "APPEND", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmAppend(p0...)
}

// gen_bridge
//
// syntax: bridge(string)
func (x *Node) gen_bridge(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("bridge", 1, len(args))
	}
	p0, err := convString(args, 0, "bridge", "string")
	if err != nil {
		return nil, err
	}
	ret := x.fmBridge(p0)
	return ret, nil
}

// gen_BRIDGE_QUERY
//
// syntax: BRIDGE_QUERY(string, string, ...interface {})
func (x *Node) gen_BRIDGE_QUERY(args ...any) (any, error) {
	if len(args) < 2 {
		return nil, ErrInvalidNumOfArgs("BRIDGE_QUERY", 2, len(args))
	}
	p0, err := convString(args, 0, "BRIDGE_QUERY", "string")
	if err != nil {
		return nil, err
	}
	p1, err := convString(args, 1, "BRIDGE_QUERY", "string")
	if err != nil {
		return nil, err
	}
	p2 := []interface{}{}
	for n := 2; n < len(args); n++ {
		argv, err := convAny(args, n, "BRIDGE_QUERY", "...interface {}")
		if err != nil {
			return nil, err
		}
		p2 = append(p2, argv)
	}
	return x.fmBridgeQuery(p0, p1, p2...)
}

// gen_minHz
//
// syntax: minHz(float64)
func (x *Node) gen_minHz(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("minHz", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "minHz", "float64")
	if err != nil {
		return nil, err
	}
	ret := x.fmMinHz(p0)
	return ret, nil
}

// gen_maxHz
//
// syntax: maxHz(float64)
func (x *Node) gen_maxHz(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("maxHz", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "maxHz", "float64")
	if err != nil {
		return nil, err
	}
	ret := x.fmMaxHz(p0)
	return ret, nil
}

// gen_FFT
//
// syntax: FFT(...interface {})
func (x *Node) gen_FFT(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "FFT", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmFastFourierTransform(p0...)
}

// gen_CSV
//
// syntax: CSV(...interface {})
func (x *Node) gen_CSV(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CSV", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmCsv(p0...)
}

// gen_JSON
//
// syntax: JSON(...interface {})
func (x *Node) gen_JSON(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "JSON", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmJson(p0...)
}

// gen_MARKDOWN
//
// syntax: MARKDOWN(...interface {})
func (x *Node) gen_MARKDOWN(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "MARKDOWN", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmMarkdown(p0...)
}

// gen_HTML
//
// syntax: HTML(...interface {})
func (x *Node) gen_HTML(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "HTML", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmHtml(p0...)
}

// gen_CHART
//
// syntax: CHART(...interface {})
func (x *Node) gen_CHART(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CHART", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmChart(p0...)
}

// gen_CHART_LINE
//
// syntax: CHART_LINE(...interface {})
func (x *Node) gen_CHART_LINE(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CHART_LINE", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmChartLine(p0...)
}

// gen_CHART_SCATTER
//
// syntax: CHART_SCATTER(...interface {})
func (x *Node) gen_CHART_SCATTER(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CHART_SCATTER", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmChartScatter(p0...)
}

// gen_CHART_BAR
//
// syntax: CHART_BAR(...interface {})
func (x *Node) gen_CHART_BAR(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CHART_BAR", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmChartBar(p0...)
}

// gen_CHART_LINE3D
//
// syntax: CHART_LINE3D(...interface {})
func (x *Node) gen_CHART_LINE3D(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CHART_LINE3D", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmChartLine3D(p0...)
}

// gen_CHART_BAR3D
//
// syntax: CHART_BAR3D(...interface {})
func (x *Node) gen_CHART_BAR3D(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CHART_BAR3D", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmChartBar3D(p0...)
}

// gen_CHART_SURFACE3D
//
// syntax: CHART_SURFACE3D(...interface {})
func (x *Node) gen_CHART_SURFACE3D(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CHART_SURFACE3D", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmChartSurface3D(p0...)
}

// gen_CHART_SCATTER3D
//
// syntax: CHART_SCATTER3D(...interface {})
func (x *Node) gen_CHART_SCATTER3D(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "CHART_SCATTER3D", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmChartScatter3D(p0...)
}

// gen_separator
//
// syntax: separator(uint8)
func (x *Node) gen_separator(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("separator", 1, len(args))
	}
	p0, err := convByte(args, 0, "separator", "uint8")
	if err != nil {
		return nil, err
	}
	ret := x.fmSeparator(p0)
	return ret, nil
}

// gen_trimspace
//
// syntax: trimspace(bool)
func (x *Node) gen_trimspace(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("trimspace", 1, len(args))
	}
	p0, err := convBool(args, 0, "trimspace", "bool")
	if err != nil {
		return nil, err
	}
	ret := x.fmTrimSpace(p0)
	return ret, nil
}

// gen_file
//
// syntax: file(string)
func (x *Node) gen_file(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("file", 1, len(args))
	}
	p0, err := convString(args, 0, "file", "string")
	if err != nil {
		return nil, err
	}
	return x.fmFile(p0)
}

// gen_STRING
//
// syntax: STRING(, ...interface {})
func (x *Node) gen_STRING(args ...any) (any, error) {
	if len(args) < 1 {
		return nil, ErrInvalidNumOfArgs("STRING", 1, len(args))
	}
	p0, err := convAny(args, 0, "STRING", "interface {}")
	if err != nil {
		return nil, err
	}
	p1 := []interface{}{}
	for n := 1; n < len(args); n++ {
		argv, err := convAny(args, n, "STRING", "...interface {}")
		if err != nil {
			return nil, err
		}
		p1 = append(p1, argv)
	}
	return x.fmString(p0, p1...)
}

// gen_BYTES
//
// syntax: BYTES(, ...interface {})
func (x *Node) gen_BYTES(args ...any) (any, error) {
	if len(args) < 1 {
		return nil, ErrInvalidNumOfArgs("BYTES", 1, len(args))
	}
	p0, err := convAny(args, 0, "BYTES", "interface {}")
	if err != nil {
		return nil, err
	}
	p1 := []interface{}{}
	for n := 1; n < len(args); n++ {
		argv, err := convAny(args, n, "BYTES", "...interface {}")
		if err != nil {
			return nil, err
		}
		p1 = append(p1, argv)
	}
	return x.fmBytes(p0, p1...)
}

// gen_col
//
// syntax: col(...interface {})
func (x *Node) gen_col(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "col", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmCol(p0...)
}

// gen_field
//
// syntax: field(...interface {})
func (x *Node) gen_field(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "field", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmField(p0...)
}

// gen_datetimeType
//
// syntax: datetimeType(...interface {})
func (x *Node) gen_datetimeType(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "datetimeType", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmDatetimeType(p0...)
}

// gen_stringType
//
// syntax: stringType(...interface {})
func (x *Node) gen_stringType(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "stringType", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmStringType(p0...)
}

// gen_doubleType
//
// syntax: doubleType(...interface {})
func (x *Node) gen_doubleType(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "doubleType", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmDoubleType(p0...)
}

// gen_freq
//
// syntax: freq(float64, float64, ...float64)
func (x *Node) gen_freq(args ...any) (any, error) {
	if len(args) < 2 {
		return nil, ErrInvalidNumOfArgs("freq", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "freq", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "freq", "float64")
	if err != nil {
		return nil, err
	}
	p2 := []float64{}
	for n := 2; n < len(args); n++ {
		argv, err := convFloat64(args, n, "freq", "...float64")
		if err != nil {
			return nil, err
		}
		p2 = append(p2, argv)
	}
	ret := x.fmFreq(p0, p1, p2...)
	return ret, nil
}

// gen_oscillator
//
// syntax: oscillator(...interface {})
func (x *Node) gen_oscillator(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "oscillator", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmOscillator(p0...)
}

// gen_sphere
//
// syntax: sphere(float64, float64)
func (x *Node) gen_sphere(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("sphere", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "sphere", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "sphere", "float64")
	if err != nil {
		return nil, err
	}
	ret := x.fmSphere(p0, p1)
	return ret, nil
}

// gen_FAKE
//
// syntax: FAKE()
func (x *Node) gen_FAKE(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("FAKE", 1, len(args))
	}
	p0, err := convAny(args, 0, "FAKE", "interface {}")
	if err != nil {
		return nil, err
	}
	return x.fmFake(p0)
}

// gen_INPUT
//
// syntax: INPUT(...interface {})
func (x *Node) gen_INPUT(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "INPUT", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmINPUT(p0...)
}

// gen_OUTPUT
//
// syntax: OUTPUT(...interface {})
func (x *Node) gen_OUTPUT(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "OUTPUT", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	return x.fmOUTPUT(p0...)
}

// gen_tz
//
// syntax: tz(string)
func (x *Node) gen_tz(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("tz", 1, len(args))
	}
	p0, err := convString(args, 0, "tz", "string")
	if err != nil {
		return nil, err
	}
	return x.fmTZ(p0)
}

// gen_sep
//
// syntax: sep(uint8)
func (x *Node) gen_sep(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("sep", 1, len(args))
	}
	p0, err := convByte(args, 0, "sep", "uint8")
	if err != nil {
		return nil, err
	}
	ret := x.fmSeparator(p0)
	return ret, nil
}

// gen_assetHost
//
// syntax: assetHost(string)
func (x *Node) gen_assetHost(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("assetHost", 1, len(args))
	}
	p0, err := convString(args, 0, "assetHost", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.AssetHost(p0)
	return ret, nil
}

// gen_autoRotate
//
// syntax: autoRotate(float64)
func (x *Node) gen_autoRotate(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("autoRotate", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "autoRotate", "float64")
	if err != nil {
		return nil, err
	}
	ret := opts.AutoRotate(p0)
	return ret, nil
}

// gen_boxDrawBorder
//
// syntax: boxDrawBorder(bool)
func (x *Node) gen_boxDrawBorder(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("boxDrawBorder", 1, len(args))
	}
	p0, err := convBool(args, 0, "boxDrawBorder", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.BoxDrawBorder(p0)
	return ret, nil
}

// gen_boxSeparateColumns
//
// syntax: boxSeparateColumns(bool)
func (x *Node) gen_boxSeparateColumns(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("boxSeparateColumns", 1, len(args))
	}
	p0, err := convBool(args, 0, "boxSeparateColumns", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.BoxSeparateColumns(p0)
	return ret, nil
}

// gen_boxStyle
//
// syntax: boxStyle(string)
func (x *Node) gen_boxStyle(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("boxStyle", 1, len(args))
	}
	p0, err := convString(args, 0, "boxStyle", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.BoxStyle(p0)
	return ret, nil
}

// gen_brief
//
// syntax: brief(bool)
func (x *Node) gen_brief(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("brief", 1, len(args))
	}
	p0, err := convBool(args, 0, "brief", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.Brief(p0)
	return ret, nil
}

// gen_briefCount
//
// syntax: briefCount(int)
func (x *Node) gen_briefCount(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("briefCount", 1, len(args))
	}
	p0, err := convInt(args, 0, "briefCount", "int")
	if err != nil {
		return nil, err
	}
	ret := opts.BriefCount(p0)
	return ret, nil
}

// gen_chartJson
//
// syntax: chartJson(bool)
func (x *Node) gen_chartJson(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("chartJson", 1, len(args))
	}
	p0, err := convBool(args, 0, "chartJson", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.ChartJson(p0)
	return ret, nil
}

// gen_columnTypes
//
// syntax: columnTypes(...string)
func (x *Node) gen_columnTypes(args ...any) (any, error) {
	p0 := []string{}
	for n := 0; n < len(args); n++ {
		argv, err := convString(args, n, "columnTypes", "...string")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.ColumnTypes(p0...)
	return ret, nil
}

// gen_columns
//
// syntax: columns(...string)
func (x *Node) gen_columns(args ...any) (any, error) {
	p0 := []string{}
	for n := 0; n < len(args); n++ {
		argv, err := convString(args, n, "columns", "...string")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.Columns(p0...)
	return ret, nil
}

// gen_dataZoom
//
// syntax: dataZoom(string, float32, float32)
func (x *Node) gen_dataZoom(args ...any) (any, error) {
	if len(args) != 3 {
		return nil, ErrInvalidNumOfArgs("dataZoom", 3, len(args))
	}
	p0, err := convString(args, 0, "dataZoom", "string")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat32(args, 1, "dataZoom", "float32")
	if err != nil {
		return nil, err
	}
	p2, err := convFloat32(args, 2, "dataZoom", "float32")
	if err != nil {
		return nil, err
	}
	ret := opts.DataZoom(p0, p1, p2)
	return ret, nil
}

// gen_delimiter
//
// syntax: delimiter(string)
func (x *Node) gen_delimiter(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("delimiter", 1, len(args))
	}
	p0, err := convString(args, 0, "delimiter", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.Delimiter(p0)
	return ret, nil
}

// gen_global
//
// syntax: global(string)
func (x *Node) gen_global(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("global", 1, len(args))
	}
	p0, err := convString(args, 0, "global", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.Global(p0)
	return ret, nil
}

// gen_globalOptions
//
// syntax: globalOptions(string)
func (x *Node) gen_globalOptions(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("globalOptions", 1, len(args))
	}
	p0, err := convString(args, 0, "globalOptions", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.GlobalOptions(p0)
	return ret, nil
}

// gen_gridSize
//
// syntax: gridSize(...float64)
func (x *Node) gen_gridSize(args ...any) (any, error) {
	p0 := []float64{}
	for n := 0; n < len(args); n++ {
		argv, err := convFloat64(args, n, "gridSize", "...float64")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.GridSize(p0...)
	return ret, nil
}

// gen_header
//
// syntax: header(bool)
func (x *Node) gen_header(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("header", 1, len(args))
	}
	p0, err := convBool(args, 0, "header", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.Header(p0)
	return ret, nil
}

// gen_heading
//
// syntax: heading(bool)
func (x *Node) gen_heading(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("heading", 1, len(args))
	}
	p0, err := convBool(args, 0, "heading", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.Heading(p0)
	return ret, nil
}

// gen_html
//
// syntax: html(bool)
func (x *Node) gen_html(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("html", 1, len(args))
	}
	p0, err := convBool(args, 0, "html", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.Html(p0)
	return ret, nil
}

// gen_inputStream
//
// syntax: inputStream(InputStream)
func (x *Node) gen_inputStream(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("inputStream", 1, len(args))
	}
	p0, err := convInputStream(args, 0, "inputStream", "spec.InputStream")
	if err != nil {
		return nil, err
	}
	ret := opts.InputStream(p0)
	return ret, nil
}

// gen_lineWidth
//
// syntax: lineWidth(float64)
func (x *Node) gen_lineWidth(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("lineWidth", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "lineWidth", "float64")
	if err != nil {
		return nil, err
	}
	ret := opts.LineWidth(p0)
	return ret, nil
}

// gen_logger
//
// syntax: logger(Logger)
func (x *Node) gen_logger(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("logger", 1, len(args))
	}
	p0, err := convLogger(args, 0, "logger", "logger.Logger")
	if err != nil {
		return nil, err
	}
	ret := opts.Logger(p0)
	return ret, nil
}

// gen_markAreaNameCoord
//
// syntax: markAreaNameCoord(, , string, string, float64)
func (x *Node) gen_markAreaNameCoord(args ...any) (any, error) {
	if len(args) != 5 {
		return nil, ErrInvalidNumOfArgs("markAreaNameCoord", 5, len(args))
	}
	p0, err := convAny(args, 0, "markAreaNameCoord", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "markAreaNameCoord", "interface {}")
	if err != nil {
		return nil, err
	}
	p2, err := convString(args, 2, "markAreaNameCoord", "string")
	if err != nil {
		return nil, err
	}
	p3, err := convString(args, 3, "markAreaNameCoord", "string")
	if err != nil {
		return nil, err
	}
	p4, err := convFloat64(args, 4, "markAreaNameCoord", "float64")
	if err != nil {
		return nil, err
	}
	ret := opts.MarkAreaNameCoord(p0, p1, p2, p3, p4)
	return ret, nil
}

// gen_markAreaXAxis
//
// syntax: markAreaXAxis(int, , , string)
func (x *Node) gen_markAreaXAxis(args ...any) (any, error) {
	if len(args) != 4 {
		return nil, ErrInvalidNumOfArgs("markAreaXAxis", 4, len(args))
	}
	p0, err := convInt(args, 0, "markAreaXAxis", "int")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "markAreaXAxis", "interface {}")
	if err != nil {
		return nil, err
	}
	p2, err := convAny(args, 2, "markAreaXAxis", "interface {}")
	if err != nil {
		return nil, err
	}
	p3, err := convString(args, 3, "markAreaXAxis", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.MarkAreaXAxis(p0, p1, p2, p3)
	return ret, nil
}

// gen_markAreaYAxis
//
// syntax: markAreaYAxis(int, , , string)
func (x *Node) gen_markAreaYAxis(args ...any) (any, error) {
	if len(args) != 4 {
		return nil, ErrInvalidNumOfArgs("markAreaYAxis", 4, len(args))
	}
	p0, err := convInt(args, 0, "markAreaYAxis", "int")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "markAreaYAxis", "interface {}")
	if err != nil {
		return nil, err
	}
	p2, err := convAny(args, 2, "markAreaYAxis", "interface {}")
	if err != nil {
		return nil, err
	}
	p3, err := convString(args, 3, "markAreaYAxis", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.MarkAreaYAxis(p0, p1, p2, p3)
	return ret, nil
}

// gen_markLineStyle
//
// syntax: markLineStyle(int, string)
func (x *Node) gen_markLineStyle(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("markLineStyle", 2, len(args))
	}
	p0, err := convInt(args, 0, "markLineStyle", "int")
	if err != nil {
		return nil, err
	}
	p1, err := convString(args, 1, "markLineStyle", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.MarkLineStyle(p0, p1)
	return ret, nil
}

// gen_markLineXAxis
//
// syntax: markLineXAxis(int, )
func (x *Node) gen_markLineXAxis(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("markLineXAxis", 2, len(args))
	}
	p0, err := convInt(args, 0, "markLineXAxis", "int")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "markLineXAxis", "interface {}")
	if err != nil {
		return nil, err
	}
	ret := opts.MarkLineXAxis(p0, p1)
	return ret, nil
}

// gen_markLineXAxisCoord
//
// syntax: markLineXAxisCoord(, string)
func (x *Node) gen_markLineXAxisCoord(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("markLineXAxisCoord", 2, len(args))
	}
	p0, err := convAny(args, 0, "markLineXAxisCoord", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convString(args, 1, "markLineXAxisCoord", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.MarkLineXAxisCoord(p0, p1)
	return ret, nil
}

// gen_markLineYAxis
//
// syntax: markLineYAxis(int, )
func (x *Node) gen_markLineYAxis(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("markLineYAxis", 2, len(args))
	}
	p0, err := convInt(args, 0, "markLineYAxis", "int")
	if err != nil {
		return nil, err
	}
	p1, err := convAny(args, 1, "markLineYAxis", "interface {}")
	if err != nil {
		return nil, err
	}
	ret := opts.MarkLineYAxis(p0, p1)
	return ret, nil
}

// gen_markLineYAxisCoord
//
// syntax: markLineYAxisCoord(, string)
func (x *Node) gen_markLineYAxisCoord(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("markLineYAxisCoord", 2, len(args))
	}
	p0, err := convAny(args, 0, "markLineYAxisCoord", "interface {}")
	if err != nil {
		return nil, err
	}
	p1, err := convString(args, 1, "markLineYAxisCoord", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.MarkLineYAxisCoord(p0, p1)
	return ret, nil
}

// gen_opacity
//
// syntax: opacity(float64)
func (x *Node) gen_opacity(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("opacity", 1, len(args))
	}
	p0, err := convFloat64(args, 0, "opacity", "float64")
	if err != nil {
		return nil, err
	}
	ret := opts.Opacity(p0)
	return ret, nil
}

// gen_outputStream
//
// syntax: outputStream(OutputStream)
func (x *Node) gen_outputStream(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("outputStream", 1, len(args))
	}
	p0, err := convOutputStream(args, 0, "outputStream", "spec.OutputStream")
	if err != nil {
		return nil, err
	}
	ret := opts.OutputStream(p0)
	return ret, nil
}

// gen_precision
//
// syntax: precision(int)
func (x *Node) gen_precision(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("precision", 1, len(args))
	}
	p0, err := convInt(args, 0, "precision", "int")
	if err != nil {
		return nil, err
	}
	ret := opts.Precision(p0)
	return ret, nil
}

// gen_rownum
//
// syntax: rownum(bool)
func (x *Node) gen_rownum(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("rownum", 1, len(args))
	}
	p0, err := convBool(args, 0, "rownum", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.Rownum(p0)
	return ret, nil
}

// gen_series
//
// syntax: series(...string)
func (x *Node) gen_series(args ...any) (any, error) {
	p0 := []string{}
	for n := 0; n < len(args); n++ {
		argv, err := convString(args, n, "series", "...string")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.Series(p0...)
	return ret, nil
}

// gen_seriesLabels
//
// syntax: seriesLabels(...string)
func (x *Node) gen_seriesLabels(args ...any) (any, error) {
	p0 := []string{}
	for n := 0; n < len(args); n++ {
		argv, err := convString(args, n, "seriesLabels", "...string")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.SeriesLabels(p0...)
	return ret, nil
}

// gen_seriesOptions
//
// syntax: seriesOptions(...string)
func (x *Node) gen_seriesOptions(args ...any) (any, error) {
	p0 := []string{}
	for n := 0; n < len(args); n++ {
		argv, err := convString(args, n, "seriesOptions", "...string")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.SeriesOptions(p0...)
	return ret, nil
}

// gen_showGrid
//
// syntax: showGrid(bool)
func (x *Node) gen_showGrid(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("showGrid", 1, len(args))
	}
	p0, err := convBool(args, 0, "showGrid", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.ShowGrid(p0)
	return ret, nil
}

// gen_size
//
// syntax: size(string, string)
func (x *Node) gen_size(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("size", 2, len(args))
	}
	p0, err := convString(args, 0, "size", "string")
	if err != nil {
		return nil, err
	}
	p1, err := convString(args, 1, "size", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.Size(p0, p1)
	return ret, nil
}

// gen_substituteNull
//
// syntax: substituteNull(string)
func (x *Node) gen_substituteNull(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("substituteNull", 1, len(args))
	}
	p0, err := convString(args, 0, "substituteNull", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.SubstituteNull(p0)
	return ret, nil
}

// gen_subtitle
//
// syntax: subtitle(string)
func (x *Node) gen_subtitle(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("subtitle", 1, len(args))
	}
	p0, err := convString(args, 0, "subtitle", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.Subtitle(p0)
	return ret, nil
}

// gen_tableName
//
// syntax: tableName(string)
func (x *Node) gen_tableName(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("tableName", 1, len(args))
	}
	p0, err := convString(args, 0, "tableName", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.TableName(p0)
	return ret, nil
}

// gen_theme
//
// syntax: theme(string)
func (x *Node) gen_theme(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("theme", 1, len(args))
	}
	p0, err := convString(args, 0, "theme", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.Theme(p0)
	return ret, nil
}

// gen_timeLocation
//
// syntax: timeLocation()
func (x *Node) gen_timeLocation(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("timeLocation", 1, len(args))
	}
	p0, err := convTimeLocation(args, 0, "timeLocation", "*time.Location")
	if err != nil {
		return nil, err
	}
	ret := opts.TimeLocation(p0)
	return ret, nil
}

// gen_timeformat
//
// syntax: timeformat(string)
func (x *Node) gen_timeformat(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("timeformat", 1, len(args))
	}
	p0, err := convString(args, 0, "timeformat", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.Timeformat(p0)
	return ret, nil
}

// gen_title
//
// syntax: title(string)
func (x *Node) gen_title(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("title", 1, len(args))
	}
	p0, err := convString(args, 0, "title", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.Title(p0)
	return ret, nil
}

// gen_toolboxDataView
//
// syntax: toolboxDataView()
func (x *Node) gen_toolboxDataView(args ...any) (any, error) {
	if len(args) != 0 {
		return nil, ErrInvalidNumOfArgs("toolboxDataView", 0, len(args))
	}
	ret := opts.ToolboxDataView()
	return ret, nil
}

// gen_toolboxDataZoom
//
// syntax: toolboxDataZoom()
func (x *Node) gen_toolboxDataZoom(args ...any) (any, error) {
	if len(args) != 0 {
		return nil, ErrInvalidNumOfArgs("toolboxDataZoom", 0, len(args))
	}
	ret := opts.ToolboxDataZoom()
	return ret, nil
}

// gen_toolboxSaveAsImage
//
// syntax: toolboxSaveAsImage(string)
func (x *Node) gen_toolboxSaveAsImage(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("toolboxSaveAsImage", 1, len(args))
	}
	p0, err := convString(args, 0, "toolboxSaveAsImage", "string")
	if err != nil {
		return nil, err
	}
	ret := opts.ToolboxSaveAsImage(p0)
	return ret, nil
}

// gen_transcoder
//
// syntax: transcoder(Transcoder)
func (x *Node) gen_transcoder(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("transcoder", 1, len(args))
	}
	p0, err := convTranscoder(args, 0, "transcoder", "transcoder.Transcoder")
	if err != nil {
		return nil, err
	}
	ret := opts.Transcoder(p0)
	return ret, nil
}

// gen_transpose
//
// syntax: transpose(bool)
func (x *Node) gen_transpose(args ...any) (any, error) {
	if len(args) != 1 {
		return nil, ErrInvalidNumOfArgs("transpose", 1, len(args))
	}
	p0, err := convBool(args, 0, "transpose", "bool")
	if err != nil {
		return nil, err
	}
	ret := opts.Transpose(p0)
	return ret, nil
}

// gen_visualMap
//
// syntax: visualMap(float64, float64)
func (x *Node) gen_visualMap(args ...any) (any, error) {
	if len(args) != 2 {
		return nil, ErrInvalidNumOfArgs("visualMap", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "visualMap", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "visualMap", "float64")
	if err != nil {
		return nil, err
	}
	ret := opts.VisualMap(p0, p1)
	return ret, nil
}

// gen_visualMapColor
//
// syntax: visualMapColor(float64, float64, ...string)
func (x *Node) gen_visualMapColor(args ...any) (any, error) {
	if len(args) < 2 {
		return nil, ErrInvalidNumOfArgs("visualMapColor", 2, len(args))
	}
	p0, err := convFloat64(args, 0, "visualMapColor", "float64")
	if err != nil {
		return nil, err
	}
	p1, err := convFloat64(args, 1, "visualMapColor", "float64")
	if err != nil {
		return nil, err
	}
	p2 := []string{}
	for n := 2; n < len(args); n++ {
		argv, err := convString(args, n, "visualMapColor", "...string")
		if err != nil {
			return nil, err
		}
		p2 = append(p2, argv)
	}
	ret := opts.VisualMapColor(p0, p1, p2...)
	return ret, nil
}

// gen_xAxis
//
// syntax: xAxis(...interface {})
func (x *Node) gen_xAxis(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "xAxis", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.XAxis(p0...)
	return ret, nil
}

// gen_yAxis
//
// syntax: yAxis(...interface {})
func (x *Node) gen_yAxis(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "yAxis", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.YAxis(p0...)
	return ret, nil
}

// gen_zAxis
//
// syntax: zAxis(...interface {})
func (x *Node) gen_zAxis(args ...any) (any, error) {
	p0 := []interface{}{}
	for n := 0; n < len(args); n++ {
		argv, err := convAny(args, n, "zAxis", "...interface {}")
		if err != nil {
			return nil, err
		}
		p0 = append(p0, argv)
	}
	ret := opts.ZAxis(p0...)
	return ret, nil
}
