definitions:
  msg.QueryData:
    properties:
      columns:
        items:
          type: string
        type: array
      rows:
        items:
          items: {}
          type: array
        type: array
      types:
        items:
          type: string
        type: array
    type: object
  msg.QueryResponse:
    properties:
      data:
        $ref: '#/definitions/msg.QueryData'
      elapse:
        type: string
      reason:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /db/query:
    get:
      description: execute query
      parameters:
      - default: select * from example limit 3
        description: sql query text
        in: query
        name: q
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/msg.QueryResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/msg.QueryResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/msg.QueryResponse'
      summary: Execute query
swagger: "2.0"
