name: CI darwin-arm64

on:
  push:
    branches:
      - 'main'

jobs:
  builds:
    runs-on: [ macos-12 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19.6'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make package-machbase-neo
      - name: Upload nightly build
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GIT_PASS }}
          file: packages/machbase-neo-*-v*.zip
          repo_name: machbase/neo-server
          prerelease: true
          tag: nightly
          overwrite: true
          file_glob: true

