name: CI darwin-arm64

on:
  push:
    branches:
      - 'main'

jobs:
  builds:
    runs-on: [ self-hosted, macOS, ARM64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make package-machbase-neo && \
          make package-neow
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: |
            packages/machbase-neo-v*.zip
            packages/neow-v*.zip
          retention-days: 5

