name: CI linux-amd64

on:
  push:
    branches:
      - '*'

jobs:
  builds:
    runs-on: [ self-hosted, linux, X64, ubuntu18 ]
    env:
      GOPRIVATE: "github.com/machbase/*"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Branch name
        id: branch_name
        run: |
          echo "VER=`./scripts/buildversion.sh`" >> $GITHUB_OUTPUT
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          token: ${{ secrets.GIT_PASS }}
          go-version: '^1.19.5'
      - name: Build
        run: |
          make test && \
          make cleanpackage && \
          make package-machbase-neo
      - name: Artifacts
        id: id
        run: |
          cd packages && \
          echo "FILENAME_EDGE=`ls machbase-neo-edge-v*.zip`" >> $GITHUB_OUTPUT && \
          echo "FILENAME_FOG=`ls machbase-neo-fog-v*.zip`" >> $GITHUB_OUTPUT
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.id.outputs.FILENAME_EDGE }}
          path: packages/${{ steps.id.outputs.FILENAME_EDGE }}
          retention-days: 5
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.id.outputs.FILENAME_FOG }}
          path: packages/${{ steps.id.outputs.FILENAME_FOG }}
          retention-days: 5
