name: CI linux-arm32

on:
  push:
    branches:
      - 'xxxx'

jobs:
  builds:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Build
        run: make arm32package-machbase-neo
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: packages/machbase-neo-v*.zip
          retention-days: 5
