name: CI v1

on:
  push:
    branches:
      - 'main-v1'

jobs:
  linux-arm64:
    runs-on: [ self-hosted, linux, ARM64, ubuntu18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make package-machbase-neo
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: packages/machbase-neo-v*.zip
          retention-days: 5
  linux-arm32:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Build
        run: make arm32package-machbase-neo
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: packages/machbase-neo-v*.zip
          retention-days: 5
  linux-amd64:
    runs-on: [ self-hosted, linux, X64, ubuntu18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make package-machbase-neo
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: packages/machbase-neo-v*.zip
          retention-days: 5
  darwin-arm64:
    runs-on: [ self-hosted, macOS, ARM64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make package-machbase-neo && \
          make package-neow
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: |
            packages/machbase-neo-v*.zip
            packages/neow-v*.zip
          retention-days: 5
  darwin-amd64:
    runs-on: [ macos-12 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make package-machbase-neo && \
          make package-neow
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: |
            packages/machbase-neo-v*.zip
            packages/neow-v*.zip
          retention-days: 5