name: CI-PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  builds:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Install Dependencies
        run: sudo apt-get install -y libjemalloc-dev
      - name: Setup go compiler
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: Test
        run: go run mage.go test
      - name: Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build amd64
        run: go run mage.go buildx machbase-neo linux amd64 packagex machbase-neo linux amd64
      - name: Build arm32
        run: go run mage.go buildx machbase-neo linux arm packagex machbase-neo linux arm
