name: CI-PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  builds:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Branch name
        id: branch_name
        run: |
          echo "VER=`./scripts/buildversion.sh`" >> $GITHUB_OUTPUT
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Setup zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 'master'
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Test
        run: go run mage.go test
      - name: Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build amd64
        run: go run mage.go machbase-neo package-machbase-neo
      - name: Build arm32
        run: go run mage.go buildx machbase-neo linux arm packagex machbase-neo linux arm
