name: CI linux-amd64

on:
  pull_request:
    types:
      - opened

jobs:
  builds:
    runs-on: [ linux, X64 ]
    env:
      GOPRIVATE: "github.com/machbase/*"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Branch name
        id: branch_name
        run: |
          echo "VER=`./scripts/buildversion.sh`" >> $GITHUB_OUTPUT
          echo "SOURCE_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "SOURCE_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          echo "SOURCE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          token: ${{ secrets.GIT_PASS }}
          go-version: '^1.19.5'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make package-machbase-neo
