name: Releases

on:
  push:
    tags:
      - v*

jobs:
    darwin-arm64:
        runs-on: [ self-hosted, macOS, ARM64 ]
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: Setup go compiler
            uses: actions/setup-go@v3
            with:
              go-version: '1.20.7'
          - name: Build
            run: go run mage.go test machbase-neo package-machbase-neo neow package-neow
          - name: Release files
            uses: svenstaro/upload-release-action@v2
            if: startsWith(github.ref, 'refs/tags/v')
            with:
                repo_token: ${{ secrets.GIT_PASS }}
                file: packages/*neo*-v*.zip
                repo_name: machbase/neo-server
                prerelease: true
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true
    darwin-amd64:
        runs-on: [ macos-12 ]
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          - name: Setup go compiler
            uses: actions/setup-go@v3
            with:
                go-version: '1.20.7'
          - name: Build
            run: go run mage.go test machbase-neo package-machbase-neo neow package-neow
          - name: Release files
            uses: svenstaro/upload-release-action@v2
            if: startsWith(github.ref, 'refs/tags/v')
            with:
                repo_token: ${{ secrets.GIT_PASS }}
                file: packages/*neo*-v*.zip
                repo_name: machbase/neo-server
                prerelease: true
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true
    linux-amd64:
        runs-on: [ self-hosted, linux, X64, ubuntu18 ]
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          - name: Setup go compiler
            uses: actions/setup-go@v3
            with:
                go-version: '1.20.7'
          - name: Build
            run: go run mage.go test machbase-neo package-machbase-neo
          - name: Release files
            uses: svenstaro/upload-release-action@v2
            if: startsWith(github.ref, 'refs/tags/v')
            with:
                repo_token: ${{ secrets.GIT_PASS }}
                file: packages/machbase-neo-v*.zip
                repo_name: machbase/neo-server
                prerelease: true
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true
    linux-arm64:
        runs-on: [ self-hosted, linux, ARM64, ubuntu18 ]
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - name: Setup go compiler
            uses: actions/setup-go@v3
            with:
              go-version: '1.20.7'
          - name: Build
            run: go run mage.go test machbase-neo package-machbase-neo
          - name: Release files
            uses: svenstaro/upload-release-action@v2
            if: startsWith(github.ref, 'refs/tags/v')
            with:
              repo_token: ${{ secrets.GIT_PASS }}
              file: packages/machbase-neo-v*.zip
              repo_name: machbase/neo-server
              prerelease: true
              tag: ${{ github.ref }}
              overwrite: true
              file_glob: true
    linux-arm32:
        runs-on: [ ubuntu-20.04 ]
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
                fetch-depth: 0
          - name: Setup go compiler
            uses: actions/setup-go@v3
            with:
                go-version: '1.20.7'
          - uses: goto-bus-stop/setup-zig@v2
            with:
                version: 0.11.0
          - name: Build
            run: go run mage.go buildx machbase-neo linux arm packagex machbase-neo linux arm
          - name: Release files
            uses: svenstaro/upload-release-action@v2
            if: startsWith(github.ref, 'refs/tags/v')
            with:
                repo_token: ${{ secrets.GIT_PASS }}
                file: packages/machbase-neo-v*.zip
                repo_name: machbase/neo-server
                prerelease: true
                tag: ${{ github.ref }}
                overwrite: true
                file_glob: true

    windows-amd64:
        runs-on: [ windows-2022 ]
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
              ref: main
          - name: Setup go compiler
            uses: actions/setup-go@v3
            with:
              go-version: '1.20.7'
          - name: Build
            run: go run mage.go machbase-neo neow
            shell: cmd
          - name: Codesign
            uses: dlemstra/code-sign-action@v1
            with:
              certificate: '${{ secrets.CODESIGN_WIN_CERTIFICATE }}' 
              password: '${{ secrets.CODESIGN_WIN_PASS }}'
              folder: './tmp'
              recursive: false
              files: |
                machbase-neo.exe
                neow.exe
          - name: Package
            run: go run mage.go package-machbase-neo
            shell: cmd
          - name: Release files
            uses: svenstaro/upload-release-action@v2
            if: startsWith(github.ref, 'refs/tags/v')
            with:
              repo_token: ${{ secrets.GIT_PASS }}
              file: packages/machbase-neo-v*.zip
              repo_name: machbase/neo-server
              prerelease: true
              tag: ${{ github.ref }}
              overwrite: true
              file_glob: true
