name: CI windows-amd64

on:
  push:
    branches:
      - 'main'

jobs:
  builds:
    runs-on: [ windows-2022 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.8'
      - name: Test
        run: make test
      - name: Build
        run: build.cmd
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: packages/machbase-neo-*-v*.zip
          retention-days: 5

