name: Docker Release for Linux

on:
  push:
    tags:
      - v*

jobs:
  arm64:
    runs-on: [ self-hosted, linux, ARM64, ubuntu18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'

      - name: Get Next Version
        id: get_version
        run: echo "ver=$(./scripts/buildversion.sh)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Neo Test
        run: make test

      - name: Package for arm64
        run: |
          make cleanpackage && \
          ./scripts/package.sh machbase-neo linux arm64 ${{ steps.get_version.outputs.ver }} && \
          unzip packages/machbase-neo-v*.zip && \
          scp machbase-neo-v*/machbase-neo ${{ secrets.DOCKER_HOST }}:/home/ubuntu/docker-build/arm64/

  amd64:
    runs-on: [ self-hosted, linux, X64, ubuntu18 ]
    needs: [ arm64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Docker version
        run: docker -v

      - name: Get Next Version
        id: get_version
        run: echo "ver=$(./scripts/buildversion.sh)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Neo Test
        run: make test

      - name: Package for amd64
        run: |
          make cleanpackage && \
          ./scripts/package.sh machbase-neo linux amd64 ${{ steps.get_version.outputs.ver }} && \
          unzip packages/machbase-neo-v*.zip && \
          mv machbase-neo-v*/machbase-neo /home/ubuntu/docker-build/amd64/
      
      - name: Docker Login
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker Build and Push
        uses: docker/build-push-action@v4
        with:
            context: /home/ubuntu/docker-build
            file: ./scripts/Dockerfile
            platforms: linux/arm64,linux/amd64
            push: true
            tags: |
              machbase/machbase-neo:${{ steps.get_version.outputs.ver }}
              machbase/machbase-neo:latest
            
