name: CI gsc-amd64

on:
  push:
    branches:
      - 'work/gsc'

jobs:
  windows-amd64:
    runs-on: [ self-hosted, Windows, X64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'work/gsc'
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Build
        run: go run mage.go test machbase-neo neow
        shell: cmd
      - name: Codesign
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CODESIGN_WIN_CERTIFICATE }}' 
          password: '${{ secrets.CODESIGN_WIN_PASS }}'
          folder: './tmp'
          recursive: false
          files: |
            machbase-neo.exe
            neow.exe
      - name: Package
        run: go run mage.go package-machbase-neo
        shell: cmd
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: packages/machbase-neo-*.zip
  linux-amd64:
    runs-on: [ self-hosted, linux, X64, ubuntu18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'work/gsc'
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Build
        run: go run mage.go test machbase-neo package-machbase-neo
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: packages/machbase-neo-v*.zip
