# This is a basic workflow to help you get started with Actions

name: test-neo-regress

# Controls when the workflow will run
on:
  schedule:
    - cron: '15 15 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux, x64, neo-regress]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v4

      - name: rm git repo
        run: cd ~/work; rm -rf neo-server; rm -rf neo-test;
      - name: clone neo-server
        run: cd ~/work; git clone git@github.com:machbase/neo-server.git;
      - name: clone neo-test
        run: cd ~/work; git clone git@github.com:machbase/neo-test.git;
      - name: build machbase-neo
        run: cd ~/work/neo-server; make machbase-neo;
      - name: run test
        run: cd ~/work/neo-test/testsuite; ntf main.ts;
      - name: print result
        run: cd ~/work/neo-test/testsuite; cat summary.txt;
      - name: check run
        run: cd ~/work/neo-test/testsuite; cat summary.txt | grep -a RUN | grep COUNT | gawk '{print $4}' > run_count.out;
      - name: check pass
        run: cd ~/work/neo-test/testsuite; cat summary.txt | grep -a PASS | grep COUNT | gawk '{print $4}' > pass_count.out;
      - name: diff
        run: cd ~/work/neo-test/testsuite; diff run_count.out pass_count.out;
      - name: print diff error
        if: failure()
        run: cd ~/work/neo-test/testsuite; cat summary.txt | grep -aE 'DIFF|ERROR';
