name: Release windows-amd64

on:
  push:
    tags:
      - v*

jobs:
  builds:
    runs-on: [ windows-2022 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - name: Install Fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: Build
        run: build.cmd
        shell: cmd
      - name: Codesign
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.CODESIGN_WIN_CERTIFICATE }}' 
          password: '${{ secrets.CODESIGN_WIN_PASS }}'
          folder: './tmp'
          recursive: false
          files: |
            machbase-neo.exe
            neow.exe
      - name: Package
        run: buildpkg.cmd
        shell: cmd
      - name: Release files
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GIT_PASS }}
          file: packages/machbase-neo-v*.zip
          repo_name: machbase/neo-server
          prerelease: true
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
