name: Release linux-amd64

on:
  push:
    tags:
      - v*

jobs:
  builds:
    runs-on: [ ubuntu-20.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.7'
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Build
        run: make arm32package-machbase-neo
      - name: Release files
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GIT_PASS }}
          file: packages/machbase-neo-v*.zip
          repo_name: machbase/neo-server
          prerelease: true
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
