name: Release darwin-arm64

on:
  push:
    tags:
      - v*

jobs:
  builds:
    runs-on: [ self-hosted, macOS, ARM64 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go compiler
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.8'
      - name: Test
        run: make test
      - name: Build
        run: |
          make cleanpackage && \
          make package-machbase-neo && \
          make package-neow
      - name: Release files
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          repo_token: ${{ secrets.GIT_PASS }}
          file: packages/*neo*-v*.zip
          repo_name: machbase/neo-server
          prerelease: true
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
