//go:generate go run ../../codec/opts/generate.go fx

package fx

// Code generated by go generate; DO NOT EDIT.

import (
	"github.com/machbase/neo-server/mods/codec/opts"
)

var Definitions = []Definition{
	{Name: "assetHost", Func: opts.AssetHost},
	{Name: "autoRotate", Func: opts.AutoRotate},
	{Name: "boxDrawBorder", Func: opts.BoxDrawBorder},
	{Name: "boxSeparateColumns", Func: opts.BoxSeparateColumns},
	{Name: "boxStyle", Func: opts.BoxStyle},
	{Name: "brief", Func: opts.Brief},
	{Name: "briefCount", Func: opts.BriefCount},
	{Name: "chartJson", Func: opts.ChartJson},
	{Name: "columnTypes", Func: opts.ColumnTypes},
	{Name: "columns", Func: opts.Columns},
	{Name: "dataZoom", Func: opts.DataZoom},
	{Name: "delimiter", Func: opts.Delimiter},
	{Name: "gridSize", Func: opts.GridSize},
	{Name: "heading", Func: opts.Heading},
	{Name: "html", Func: opts.Html},
	{Name: "inputStream", Func: opts.InputStream},
	{Name: "lineWidth", Func: opts.LineWidth},
	{Name: "markAreaNameCoord", Func: opts.MarkAreaNameCoord},
	{Name: "markLineXAxisCoord", Func: opts.MarkLineXAxisCoord},
	{Name: "markLineYAxisCoord", Func: opts.MarkLineYAxisCoord},
	{Name: "opacity", Func: opts.Opacity},
	{Name: "outputStream", Func: opts.OutputStream},
	{Name: "precision", Func: opts.Precision},
	{Name: "rownum", Func: opts.Rownum},
	{Name: "seriesLabels", Func: opts.SeriesLabels},
	{Name: "showGrid", Func: opts.ShowGrid},
	{Name: "size", Func: opts.Size},
	{Name: "subtitle", Func: opts.Subtitle},
	{Name: "tableName", Func: opts.TableName},
	{Name: "theme", Func: opts.Theme},
	{Name: "timeLocation", Func: opts.TimeLocation},
	{Name: "timeformat", Func: opts.Timeformat},
	{Name: "title", Func: opts.Title},
	{Name: "transcoder", Func: opts.Transcoder},
	{Name: "transpose", Func: opts.Transpose},
	{Name: "visualMap", Func: opts.VisualMap},
	{Name: "xAxis", Func: opts.XAxis},
	{Name: "yAxis", Func: opts.YAxis},
	{Name: "zAxis", Func: opts.ZAxis},
}
